Repository Azure/ms-rest-azure-js, pull requests merged in 2018-11, with the labels that each got.

#74 Fix ms-rest-azure-js user agent telemetry
  lib/azureServiceClient.ts
  package.json
  test/azureServiceClientTests.ts
Labels: in progress

#77 Rename NPM package to @azure/ms-rest-azure-js
  Changelog.md
  lib/azureServiceClient.ts
  lib/baseResource.ts
  lib/cloudError.ts
  lib/credentials/cognitiveServicesCredentials.ts
  lib/lroPollStrategy.ts
  lib/lroPoller.ts
  package.json
  rollup.config.js
  samples/node-sample.ts
  test/azureServiceClientTests.ts
  test/cloudErrorTests.ts
  test/credentials/cognitiveServicesCredentialsTests.ts
  test/lroPollStrategyTests.ts
Labels: Unplanned-Sprint-126, in progress

#78 Fix npm run local to support projects with different NPM name than its directory
  .scripts/dependencies.ts
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#79 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: in progress

#80 Add Azure Pipelines configuration
  .travis.yml
  azure-pipelines.yml
  package.json
Labels: Unplanned-Sprint-126, in progress

#83 Add code owners
  .github/CODEOWNERS
Labels: Unplanned-Sprint-126, in progress

#85 Add better sourcemap support for debugging
  Changelog.md
  package.json
  rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#88 Upgrade all dependencies
  package.json
Labels: in progress
