Repository Azure/ms-rest-azure-js, pull requests merged in 2018-12, with the labels that each got.

#94 Update ms-rest-js
  package.json
  test/cloudErrorTests.ts
Labels: in progress

#92 Add isLernaPackage changes from autorest.typescript
  .scripts/dependencies.ts
  .scripts/preview.ts
  package.json
Labels: Planned-Sprint-128, Started-Sprint-127, Unplanned-Sprint-127, in progress

#96 Extract dependencies-related scripts to an external package
  .scripts/dependencies.ts
  .scripts/latest.ts
  .scripts/local.ts
  .scripts/repository.ts
  .scripts/tsconfig.json
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#90 Add no-return-await TSLint rule
  tslint.json
Labels: Planned-Sprint-127, in progress

#98 Enable coverage in ci
  .gitignore
  azure-pipelines.yml
  mocha.config.json
  package.json
  test/mocha.opts
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#99 Add package.json version check
  .scripts/checkPackageJsonVersion.ts
  azure-pipelines.yml
  package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#100 Fix dependencies scripts
  .scripts/latest.ts
  .scripts/local.ts
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#101 Add only() check
  .scripts/checkTestsForOnly.ts
  azure-pipelines.yml
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress

#102 Add checkEverything.ts
  .scripts/checkEverything.ts
  .scripts/checkForOnlyCalls.ts
  .scripts/checkPackageJsonVersion.ts
  .scripts/checkTestsForOnly.ts
  azure-pipelines.yml
  package.json
Labels: Started-Sprint-128, Unplanned-Sprint-128, in progress
