Repository Azure/ms-rest-azure-js, pull requests merged in 2018-10, with the labels that each got.

#66 Change browser to module in package.json
  package.json
Labels: in progress

#69 Remove step from scripts that changed package.json main property
  .scripts/dependencies.ts
  .scripts/latest.ts
  .scripts/local.ts
  .scripts/preview.ts
Labels: Started-Sprint-125, Unplanned-Sprint-125, in progress

#70 Change tilde to caret
  .scripts/dependencies.ts
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#71 Update script regular expressions to be non-greedy
  .scripts/dependencies.ts
  package-lock.json
  package.json
Labels: Planned-Sprint-125, Started-Sprint-125, in progress

#72 Remove package-lock.json from repository
  .gitignore
  package-lock.json
Labels: Started-Sprint-125, Unplanned-Sprint-125, in progress

#73 LRO status comparison should be case insensitive
  lib/lroPollStrategy.ts
  lib/util/constants.ts
  package.json
  test/lroPollStrategyTests.ts
Labels: Planned-Sprint-126, Started-Sprint-126, in progress
