Repository Azure/ms-rest-azure-js, pull requests merged in 2018-08, with the labels that each got.

#47 Add "sideEffects": false for webpack 4
  package.json
Labels: in progress

#48 Update ms-rest-js to v0.18 and bump to v0.13
  package-lock.json
  package.json
Labels: in progress

#46 Add HttpLongRunningOperationResponse
  lib/azureServiceClient.ts
  lib/httpLongRunningOperationResponse.ts
  lib/lroPollStrategy.ts
  package-lock.json
Labels: Planned-Sprint-122, Started-Sprint-122, in progress

#49 Export HttpLongRunningOperationResponse
  lib/msRestAzure.ts
Labels: in progress

#50 Update ms-rest-js
  package-lock.json
  package.json
Labels: in progress

#51 Various improvements to our script infrastructure
  .scripts/dependencies.js
  .scripts/dependencies.ts
  .scripts/latest.js
  .scripts/latest.ts
  .scripts/local.js
  .scripts/local.ts
  .scripts/preview.js
  .scripts/preview.ts
  .scripts/repository.ts
  package-lock.json
  package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#52 Rename HttpLongRunningOperationResponse to LROPoller
  lib/azureServiceClient.ts
  lib/httpLongRunningOperationResponse.ts
  lib/lroPollStrategy.ts
  lib/lroPoller.ts
  lib/msRestAzure.ts
  package-lock.json
  package.json
  test/azureServiceClientTests.ts
Labels: Planned-Sprint-122, Planned-Sprint-123, Started-Sprint-122, in progress

#56 Add shouldDeserialize() and operationResponseGetter() support
  lib/lroPollStrategy.ts
  package-lock.json
  package.json
  test/azureServiceClientTests.ts
  test/credentials/cognitiveServicesCredentialsTests.ts
Labels: Planned-Sprint-123, Started-Sprint-123, in progress

#53 Grab credentials.environment.baseUri if present
  lib/azureServiceClient.ts
  test/azureServiceClientTests.ts
Labels: in progress

#58 Updates for RestResponse compatibility
  lib/azureServiceClient.ts
  lib/lroPoller.ts
  package-lock.json
  package.json
Labels: in progress
